name: Step 6, Trigger Your Action

# This step listens for the learner applying a label to an issue.
# This workflow updates from step 6 to step X.

# This will run every time we apply a label to an issue.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  issues:
    types: [labeled]

permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

env:
  EXPECTED_METADATA: "second joke"

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
 

  on_my_workflow_run:

    # We will only run this action when:
    # 1. This repository isn't the template repository.
    # 2. The step is currently 6.
    # Reference: https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference: https://docs.github.com/en/actions/learn-github-actions/expression
    # We'll run Ubuntu for performance instead of Mac or Windows.
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches.

      # Update README from step 6 to step X.
      - name: Update to step X
        if: contains(github.event, ${{ env.EXPECTED_METADATA }})
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 6
          to_step: X
